### ISSUE TITLE
Unknown CMake command "PKG_GET_VARIABLE"

### ISSUE THREAD

**Issue by OlliC** [n0la/rcon#1]
Hi, 
i am trying to compile this rcon tool and i get follwoing error on the cmake step on Debian 8.6:

-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.42.1
-- Looking for arc4random_uniform
-- Looking for arc4random_uniform - not found
-- checking for module 'bash-completion'
--   found bash-completion, version 2.1
CMake Error at CMakeLists.txt:38 (PKG_GET_VARIABLE):
  Unknown CMake command "PKG_GET_VARIABLE".

-- Configuring incomplete, errors occurred!
See also "/home/gs/rcon/build/CMakeFiles/CMakeOutput.log".
See also "/home/gs/rcon/build/CMakeFiles/CMakeError.log".

**Comment by n0la** [comment]
Could you try again please with the latest master?

**Comment by OlliC** [comment]
It's working now. Thanks. Great tool. Found it through the valve developer website,
