### ISSUE TITLE
It does not return after sending the command

### ISSUE THREAD

**Issue by MGW14** [n0la/rcon#10]
Hey, when im running the command it wont return...
Ive waited 5 Minutes and nothing happens. Please help

**Comment by n0la** [comment]
Please try adding the `-1` or `--1packet` option to the command line.

**Comment by MGW14** [comment]
Now there is standing Peer: Connection closed

**Comment by n0la** [comment]
What game are you trying this on? It doesn't seem to abide by the specification.

**Comment by MGW14** [comment]
Im trying to stop a minecraft server

**Comment by n0la** [comment]
Did the command work once you passed `-1`?

**Comment by MGW14** [comment]
No, never

**Comment by n0la** [comment]
I have no minecraft server for testing, so I cannot really say what's wrong. Would you be interested in debugging this issue?

**Comment by MGW14** [comment]
Yes, i could do it.
There is one: 
With the -1 arg. in my minecraft Server log is standing RCON connection from 127.0.0.1.
Sorry for my bad English. Im only speaking german

**Comment by MGW14** [comment]
WOW Danke :D

**Comment by sfxworks** [comment]
I am also having this issue.

**Comment by sfxworks** [comment]
`[02:35:22] [RCON Listener #1/INFO]: Rcon connection from: /0:0:0:0:0:0:0:1`
Regardless if I get the password right or not, it just hangs.

**Comment by n0la** [comment]
Have you tried the `-1` option?

**Comment by sfxworks** [comment]
-1 resulted in the same event. It also did not output anything extra.

**Comment by sfxworks** [comment]
Used sponge vanilla for my test if that helps.

**Comment by MGW14** [comment]
I need Sponge because my Full BungeeCord Network needa plugins

**Comment by n0la** [comment]
Technically minecraft supports Source RCON, but I have no minecraft server (I don't own this game) to test my implementation on. Maybe minecraft does something different, or deviates from the standard in a way that I am not aware of. I will look into it.

**Comment by MGW14** [comment]
Wait... it works now, just use the external Ip adress as Host! localhost or 127.0.01 doesn‘t work for me.
Now i used mgnet.work and it works!
Still using -1. I think you should add a proxy argument. :D
