### ISSUE TITLE
Invalid auth reply, valid password?

### ISSUE THREAD

**Issue by donmuerte** [n0la/rcon#12]
While attempting to use the script to send rcon commands to my ARK servers I get an "Invalid auth reply, valid password?" response. I've triple-checked that the password is correct. Oddly, if I supply the wrong password the script simply hangs with no response at all. Is there a known compatibility issue with ARK servers?

**Comment by n0la** [comment]
It might be that the ARK servers are not 100% true to the RCON standard. Please make sure first that your shell isn't somehow interpreting your password, especially if it contains special shell characters (like $ or !). I own ARK, so I can look into any compatibility issues.

**Comment by donmuerte** [comment]
The password is just alphanumerical at the moment. I tried with and without quotes. I also created a config as explained in the instructions, but it behaves the same.

**Comment by n0la** [comment]
I did just commit a fix for the ARK servers, but over here on Linux amd64 the tool now works with ARK servers. Here is my ARK command line:

`./ShooterGameServer 'TheIsland?listen?RCONEnabled=True?RCONPort=32330?ServerAdminPassword=miaou'`

And here is the call:

`florian@scylandara ~/s/r/build> ./rcon -H localhost -P "miaou" -p 32330 -1 DoExit
Exiting...`

**Comment by n0la** [comment]
Awesome :-)

**Comment by N-Rico** [comment]
Hi, I am also trying to use this for Ark, when I specify the connection settings in the command line it works fint, but when I try to use the .rconrc config file I get the same error as mentioned above.

Any chance to get this working with the config file as well?

**Comment by n0la** [comment]
Did you set `single_packet` to `TRUE` in the `.rconrc` file?

**Comment by N-Rico** [comment]
Thanks for your reply, no I haven't, did I overlook that in the manual?

format like: "single_packet = TRUE" ?

**Comment by n0la** [comment]
Yes, try that. :)

**Comment by N-Rico** [comment]
ah got it, should be lowercase :) single_packet = **_true_**

Thanks!
