### ISSUE TITLE
libbsd package on Debian is libbsd-dev

### ISSUE THREAD

**Issue by Kadigan** [n0la/rcon#15]
You may want to include that in the readme - took me a short while to find this (made a bit more fun by the fact that there exists a libbsd0 as well).

**Comment by n0la** [comment]
Thanks, I updated the README to explain building better.

**Comment by butaford** [comment]
Added Entware repo:
https://github.com/Entware/rtndev/tree/master/rcon/patches
Thanks https://github.com/ryzhovau

Patch removes libbsd-dev dependency
https://github.com/Entware/rtndev/blob/master/rcon/patches/010-remove_libbsd_dep.patch

**Comment by n0la** [comment]
Using `rand()` without a proper seed is not recommended, as it will most likely be the same number within the same second. I do not approve of this patch.

**Comment by ryzhovau** [comment]
Thanks for explanation, I've [added](https://github.com/Entware/rtndev/blob/master/rcon/patches/010-remove_libbsd_dep.patch) random seeding to patch.

**Comment by n0la** [comment]
I am afraid it is still not good enough. Instances run at the same epoch second will generate the same id. This breaks in scripts that run rcon after one another rapidly, or when you send multiple commands in the same instance. This is the reason I used a proper RNG in the first place. I'd suggest to leave the arc4 call in there. Or properly seed rand by reading from urandom.
