### ISSUE TITLE
segfault when sending "exec server.cfg"

### ISSUE THREAD

**Issue by OlliC** [n0la/rcon#2]
Hi, 

i tried to sent the command "exec server.cfg" to an Insurgency server. I have configured an .rconrc 
config file. 

$ rcon -s ins1 exec server.cfg

(process:22411): GLib-CRITICAL **: g_byte_array_remove_range: assertion 'index_ < array->len' failed
Segmentation fault

Same with 
rcon -s ins1 "exec server.cfg"
rcon -s ins1 'exec server.cfg'

**Comment by n0la** [comment]
I have fixed this issue in master, would you mind testing it again with the master branch?

**Comment by OlliC** [comment]
$ rcon -s ins1 exec server.cfg
Peer: connection closed

Seems to work now. I can see the command being executed in the server logs.

**Comment by n0la** [comment]
Nice that it's working now. I also tested this on my insurgency server :-)

I am not quite sure why the server closes the RCON connection. I guess it reinitialises the RCON server part and thus drops all active connections.

**Comment by n0la** [comment]
Can this issue be closed then?

**Comment by OlliC** [comment]
Yes
