### ISSUE TITLE
rcon does not work on Minecraft servers

### ISSUE THREAD

**Issue by n0la** [n0la/rcon#20]
Hi,

decided to use this thread because it seems not to be fixed. I am also trying to connect a minecraft server (don´t mind the avorion hostname), MC replies with one packet but rcon does not proceed.
Will there be any more patching or should we use another tool for MC?

Regards
Martin

![grafik](https://user-images.githubusercontent.com/4319959/103253267-c08c6500-4980-11eb-9a14-e8af2e42e502.png)

_Originally posted by @martin8883 in https://github.com/n0la/rcon/issues/16#issuecomment-751918249_

**Comment by n0la** [comment]
@martin8883 Could you give the current master a try? Please also use the new `--minecraft` or `-m` option, or set "minecraft" to "TRUE" in the configuration file for it to work. Minecraft has some very odd RCON behaviour.

**Comment by martin8883** [comment]
Great, it´s working now with -m. Thank you very much!
![grafik](https://user-images.githubusercontent.com/4319959/103367096-80ce9600-4ac4-11eb-8e9e-9abe2c621de7.png)

**Comment by n0la** [comment]
Awesome!
