### ISSUE TITLE
Missing Debhelper for Debian Pkg Build

### ISSUE THREAD

**Issue by Firworksyt** [n0la/rcon#26]
On Debian 11 Bullseye(x86_64), I followed the instructions to build the Debian package and issued:
`sudo apt-get install git build-essential cmake check libbsd-dev libglib2.0-dev dpkg-dev`

Then attempted to build with `dpkg-buildpackage -b -uc -us`
Which returned:
```
dpkg-buildpackage: info: source package rcon
dpkg-buildpackage: info: source version 0.6
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Florian Stinglmayr <fstinglmayr@gmail.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper-compat (= 12)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
```

I then installed the `debhelper` package and dpkg-buildpackage built successfully. I was able to install the package and rcon appears to be functioning correctly. It seems like maybe the directions should be updated to add that additional package along with dpkg-dev. Otherwise is there a different solution to this issue I should have used instead?

**Comment by n0la** [comment]
Hi,

I have added a note that you also need `debhelper` package (alongside `dpkg-dev`) to build rcon to the README. According to the debhelper docs one does not need a build dependency to `debhelper` directly, if you build depend on `debhelper-compat`:

> This also serves as an appropriate versioned build dependency on a sufficient version of the debhelper package, so you do not need to specify a separate versioned build dependency on the debhelper package unless you need a specific point release of debhelper (such as for the introduction of a new feature or bugfix within a compatibility level).

https://manpages.debian.org/testing/debhelper/debhelper.7.en.html
