### ISSUE TITLE
rcon hangs (CoD 1.1)

### ISSUE THREAD

**Issue by ghost** [n0la/rcon#27]
Hello
I'm trying to connect to a Call of Duty patch 1.1 server.
It is hosted on a AWS VPS (debian 11).
There is no issues joining the server from the game, and use `/rcon` commands from the console.

After entering a rcon command from the vps, it hangs as you could see on the following screenshot :

![rcon hangs](https://user-images.githubusercontent.com/55389708/219871372-5e4ee06b-ddc8-49c5-9781-e3b785a0ea9c.png)

I tried to change a map without success.

Please help me

**Comment by n0la** [comment]
Have you tried passing `-m`? Some RCON servers need that.

**Comment by ghost** [comment]
I thank you for your reply

I just tried `rcon -m -H 35.181.111.67 -p 28960 -P xxxxxxx status`

I don't notice any difference

**Comment by ghost** [comment]
I noticed that to start my cod server, i have to to pass the "Private IP" instead of the "Static IP", in my start script (`+set net_ip`)

When I put the private ip in the rcon command, i get the following message : `Failed to connect to the given host/service`

I hope this info could help you to get an idea about what could be the cause of the problem.

**Comment by n0la** [comment]
I have no CoD server, so I cannot help you past this.
