### ISSUE TITLE
Compatibility with RUST servers

### ISSUE THREAD

**Issue by n0la** [n0la/rcon#4]
The tool apparently does not work with rust servers. As originally reported in #3.

**Comment by sim590** [comment]
I'm not sure what I'm doing wrong. You seem to have addressed issues with Rust servers, but I can't have it respond to me. I tried for example:

```
$ rcon -H $myserverhostname -p 28016 -P $mypass -d global.status
```

But no luck...

**Comment by n0la** [comment]
Have you tried minecraft mode?

**Comment by sim590** [comment]
I can't say. I did convert my server to web based rcon and now it works. I think that the other mode is deprecated, so it's no use. Thanks for the follow up and sorry for my late response.

**Comment by sim590** [comment]
In the web base mode, it works fine by the way!

**Comment by n0la** [comment]
> web based rcon

So it seams you switched away from `rcon` to some other software? Glad everything is working for you now though.

**Comment by sim590** [comment]
I mean the rust server option `+rcon.web`. There are two modes for rcon and one is websocket based I think. I don't really remember the signification of `+rcon.web 0`, but that is what I'm using and running the following just worked:
```
$ rcon -H $myserverhostname -p 28016 -P $mypass -d global.status
```
