### ISSUE TITLE
Trying to run on ubuntu with Xonotic

### ISSUE THREAD

**Issue by fstltna** [n0la/rcon#9]
I'm trying to run this on my Xonotic server under ubuntu 16.04 but nomatter what settings I use I get a

Failed to connect to the given host/service

Is there a certain port that rcon looks for? My game server port is 26000... Any ideas on what to check?

**Comment by n0la** [comment]
My I ask how you called ```rcon```? You can pass a port as command line parameter:

```bash
$ rcon -H $host -p 26000 status
```

**Comment by n0la** [comment]
A month without any additional feedback or answers. Closing.
